import { Inter } from 'next/font/google'
import '../globals.css'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'UI Components',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html
            lang="en"
            className={cn(
                inter.className,
                `bg-background text-foreground antialiased`,
            )}
        >
            <body>{children}</body>
        </html>
    )
}
