-- 所有 seed 的数据都已经导出，暂时不需要 seed 了。
-- -- Insert album
-- insert into
--     public .album (title)
-- values
--     ('Test Track Postion Album'),
--     ('Test Error Album');
-- -- Insert track for album 100
-- insert into
--     public .track (
--         title,
--         transcription,
--         storage_path,
--         position_index,
--         album_id
--     )
-- values
--     (
--         'Track 1',
--         '[{"type":"content","text":"这是第一句话","endTime":9999}]',
--         'track_1.mp3',
--         1,
--         (
--             select
--                 id
--             from
--                 public .album
--             where
--                 title = 'Test Track Postion Album'
--         )
--     ),
--     (
--         'Track 2',
--         '[{"type":"content","text":"这是第一句话","endTime":9999}]',
--         'track_2.mp3',
--         2,
--         (
--             select
--                 id
--             from
--                 public .album
--             where
--                 title = 'Test Track Postion Album'
--         )
--     ),
--     (
--         'Track 3',
--         '[{"type":"content","text":"这是第一句话","endTime":9999}]',
--         'track_1.mp3',
--         3,
--         (
--             select
--                 id
--             from
--                 public .album
--             where
--                 title = 'Test Track Postion Album'
--         )
--     );
-- -- Insert track for album 101
-- insert into
--     public .track (
--         title,
--         transcription,
--         storage_path,
--         position_index,
--         album_id
--     )
-- values
--     (
--         'Track 1: transcription validation error',
--         '[{"type999":"content","text":"这是第一句话","endTime":9999}]',
--         'track_1.mp3',
--         1,
--         (
--             select
--                 id
--             from
--                 public .album
--             where
--                 title = 'Test Error Album'
--         )
--     ),
--     (
--         'Track 2: audio not found',
--         '[{"type":"content","text":"这是第一句话","endTime":9999}]',
--         'not-found.mp3',
--         2,
--         (
--             select
--                 id
--             from
--                 public .album
--             where
--                 title = 'Test Error Album'
--         )
--     );